export const Portofolio1=[
    {
        id:1,
        name:"Duplicate",
        href:"https://kulogroup.com/kedaikopikulo",
        judul:"React-js",
        paragraf:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
        Tujuan : "untuk melatih skill dalam bidang pembuatan tampilan user serta untuk menambah wawasan tentang hal-hal baru. Tidak ada maksud negatif.",
        objek:"Kedai Kopi Kulo",
        image:require("../../plugin/img/portofolio-img/kulo.jpg"),
        image2:require("../../plugin/img/portofolio-img/kulo2.png"),
        image3:require("../../plugin/img/portofolio-img/kulo3.png"),
        link:"https://justnitha.github.io/testing-react",
        code:"https://github.com/justnitha/testing-react",
    },
    {
        id:5,
        name:"Duplicate",
        href:"https://myphotographbali.my.id/robet-sangayu/?to=Nama%20Tamu",
        judul:"React-js",
        paragraf:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
        Tujuan : "untuk melatih skill dalam bidang pembuatan tampilan user serta untuk menambah wawasan tentang hal-hal baru. Tidak ada maksud negatif.",
        objek:"Weding",
        image:require("../../plugin/img/portofolio-img/Wedding-1.png"),
        image2:require("../../plugin/img/portofolio-img/Wedding-2.png"),
        image3:require("../../plugin/img/portofolio-img/Wedding-3.png"),
        link:"https://justnitha.github.io/undangan",
        code:"https://github.com/justnitha/undangan",
    },
    {
        id:3,
        name:"Duplicate",
        href:"https://naskleeng-13.com/",
        judul:"React-js",
        paragraf:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
        Tujuan : "untuk melatih skill dalam bidang pembuatan tampilan user serta untuk menambah wawasan tentang hal-hal baru. Tidak ada maksud negatif.",
        objek:"Naskleng-13",
        image:require("../../plugin/img/portofolio-img/baju1.png"),
        image2:require("../../plugin/img/portofolio-img/baju2.png"),
        image3:require("../../plugin/img/portofolio-img/baju3.png"),
        link:"https://justnitha.github.io/toko-baju/",
        code:"https://github.com/justnitha/toko-baju",
    },
    {
        id:4,
        name:"Duplicate",
        href:"",
        judul:"React-js",
        paragraf:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
        Tujuan : "untuk melatih skill dalam bidang pembuatan tampilan user serta untuk menambah wawasan tentang hal-hal baru. Tidak ada maksud negatif.",
        objek:"Portofolio Pertama",
        image:require("../../plugin/img/portofolio-img/porto-1.png"),
        image2:require("../../plugin/img/portofolio-img/porto-2.png"),
        image3:require("../../plugin/img/portofolio-img/porto-3.png"),
        link:"https://justnitha.github.io",
        code:"https://github.com/justnitha/justnitha.github.io",
    },
    {
        id:2,
        name:"Duplicate",
        href:"https://app.smartbtw.com/app#/",
        judul:"React-js",
        paragraf:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
        Tujuan : "untuk melatih skill dalam bidang pembuatan tampilan user serta untuk menambah wawasan tentang hal-hal baru. Tidak ada maksud negatif.",
        objek:"SmartBTW",
        image:require("../../plugin/img/portofolio-img/smart1.png"),
        image2:require("../../plugin/img/portofolio-img/smart2.png"),
        image3:require("../../plugin/img/portofolio-img/smart3.png"),
        link:"https://justnitha.github.io/react_soal",
        code:"https://github.com/justnitha/react_soal",
    },
]